spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    groups-order: desc