spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    num-partition: 3
    num-replica-factor: 1
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    listener:
      concurrency: 3
    admin:
      client-id: order-service-admin
order-service:
  order-topic: order_topic-value