spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin123
      database: database
      authentication-database: admin
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    num-partition: 3
    num-replica-factor: 1
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
    listener:
      concurrency: 3
    admin:
      client-id: notification-service-admin

notification-service:
  payment-topic: payment_topic-value
  order-topic: order_topic-value

server:
  port: 8060