spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8060/api/v1/products
    payment-url: http://localhost:8070/api/v1/payments